---
- name: Setup SSH keys, configure sudo and randomize password for ansible user on remote servers
  hosts: all
  become: yes

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Add SSH key to authorized_keys for ansible user
      authorized_key:
        user: ansible
        key: "{{ lookup('file', '/home/ric/.ssh/id_rsa.pub') }}"
        state: present

    - name: Configure passwordless sudo for ansible user
      lineinfile:
        path: /etc/sudoers.d/ansible
        create: yes
        state: present
        line: "ansible ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'

    - name: Generate a random password for the ansible user
      shell: |
        echo $(</dev/urandom tr -dc 'A-Za-z0-9!@#$%^&*()_+=-' | head -c 16; echo)
      register: random_password

    - name: Set the generated random password for the ansible user
      user:
        name: ansible
        password: "{{ random_password.stdout | password_hash('sha512') }}"
